### ISSUE TITLE
invalid syntax on el7

### ISSUE THREAD

**Issue by djgalloway** [sebastian-philipp/registries-conf-ctl#1]
```
[root@gibba019 ~]# lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.8.2003 (Core)
Release:	7.8.2003
Codename:	Core

[root@gibba019 ~]# cat /etc/containers/registries.conf | egrep -v "(^#.*|^$)"
[registries.search]
registries = ['registry.access.redhat.com', 'registry.redhat.io', 'docker.io']
[registries.insecure]
registries = []
[registries.block]
registries = []

[root@gibba019 ~]# /usr/bin/registries-conf-ctl --conf=/etc/containers/registries.conf add-mirror docker.io docker-mirror.front.sepia.ceph.com:5000
Traceback (most recent call last):
  File "/usr/bin/registries-conf-ctl", line 9, in <module>
    load_entry_point('registries-conf-ctl==1.0', 'console_scripts', 'registries-conf-ctl')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/registries_conf_ctl/cli.py", line 24
    def add_mirror(self, reg: str, mirror: str, insecure: bool, http: bool) -> None:
                            ^
SyntaxError: invalid syntax
```

**Comment by sebastian-philipp** [comment]
python2.7 strikes again. I'll convert it back tomorrow.

**Comment by djgalloway** [comment]
Could that also possibly be why after I `pip install` the tool as root, it's not in the path immediately after?

**Comment by sebastian-philipp** [comment]
fixed
