### ISSUE TITLE
Fails on CentOS8

### ISSUE THREAD

**Issue by djgalloway** [sebastian-philipp/registries-conf-ctl#5]
```
[root@braggi04 ~]# PATH=/usr/local/bin:/usr/bin registries-conf-ctl add-mirror docker.io "docker-mirror.front.sepia.ceph.com:5000"
Traceback (most recent call last):
  File "/usr/local/bin/registries-conf-ctl", line 11, in <module>
    load_entry_point('registries-conf-ctl==1.0', 'console_scripts', 'registries-conf-ctl')()
  File "/usr/local/lib/python3.6/site-packages/registries_conf_ctl/cli.py", line 195, in main
    'Failed to read any file')
  File "/usr/local/lib/python3.6/site-packages/registries_conf_ctl/cli.py", line 156, in _raise_if_all_fail
    raise ValueError('{what}: {e}'.format(what=what,e=e))
ValueError: Failed to read any file: [Errno 2] No such file or directory: '/etc/docker/daemon.json'

[root@braggi04 ~]# rpm -qa | grep 'docker\|podman'
podman-docker-3.0.0-3.el8.noarch
podman-3.0.0-3.el8.x86_64
podman-plugins-3.0.0-3.el8.x86_64
```

Not sure why it's trying docker's conf.

**Comment by sebastian-philipp** [comment]
probably introduced by podman 3

**Comment by sebastian-philipp** [comment]
Error messages should now make sense!

**Comment by djgalloway** [comment]
Still having trouble.

```
[root@braggi04 ~]# rpm -qa | grep docker
podman-docker-3.3.1-9.module_el8.5.0+988+b1f0b741.noarch
[root@braggi04 ~]# rpm -qa | grep podman
podman-catatonit-3.3.1-9.module_el8.5.0+988+b1f0b741.x86_64
podman-docker-3.3.1-9.module_el8.5.0+988+b1f0b741.noarch
podman-3.3.1-9.module_el8.5.0+988+b1f0b741.x86_64
```

```
fatal: [braggi04.front.sepia.ceph.com]: FAILED! => {
    "changed": true, 
    "cmd": [
        "registries-conf-ctl", 
        "add-mirror", 
        "docker.io", 
        "docker-mirror.front.sepia.ceph.com:5000"
    ], 
    "delta": "0:00:00.177003", 
    "end": "2021-12-15 14:57:53.606538", 
    "invocation": {
        "module_args": {
            "_raw_params": "registries-conf-ctl add-mirror docker.io \"docker-mirror.front.sepia.ceph.com:5000\"", 
            "_uses_shell": false, 
            "argv": null, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "stdin": null, 
            "stdin_add_newline": true, 
            "strip_empty_ends": true, 
            "warn": true
        }
    }, 
    "msg": "non-zero return code", 
    "rc": 1, 
    "start": "2021-12-15 14:57:53.429535", 
    "stderr": "Failed to read configuration:\n* 'unqualified-search-registries'\n* [Errno 2] No such file or directory: '/etc/docker/daemon.json'", 
    "stderr_lines": [
        "Failed to read configuration:", 
        "* 'unqualified-search-registries'", 
        "* [Errno 2] No such file or directory: '/etc/docker/daemon.json'"
    ], 
    "stdout": "", 
    "stdout_lines": []
}
```

**Comment by djgalloway** [comment]
Do you need to update a version number or anything?

```
bash-4.4$ sudo pip3 install -U git+https://github.com/sebastian-philipp/registries-conf-ctl
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting git+https://github.com/sebastian-philipp/registries-conf-ctl
  Cloning https://github.com/sebastian-philipp/registries-conf-ctl to /tmp/pip-lcfmm5ot-build
Requirement already up-to-date: toml in /usr/local/lib/python3.6/site-packages (from registries-conf-ctl==1.0)
Requirement already up-to-date: docopt in /usr/local/lib/python3.6/site-packages (from registries-conf-ctl==1.0)
Installing collected packages: registries-conf-ctl
  Found existing installation: registries-conf-ctl 1.0
    Uninstalling registries-conf-ctl-1.0:
      Successfully uninstalled registries-conf-ctl-1.0
  Running setup.py install for registries-conf-ctl ... done
Successfully installed registries-conf-ctl-1.0
bash-4.4$ registries-conf-ctl add-mirror docker.io "docker-mirror.front.sepia.ceph.com:5000"
Failed to read configuration:
* 'prefix'
* [Errno 2] No such file or directory: '/etc/docker/daemon.json'
bash-4.4$ registries-conf-ctl --version
1.0
```
